# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright © 2025 Malifex LLC and contributors

name: meNexus-dev

services:
  db:
    image: postgres:18-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=menexus_dev
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d menexus_dev"]
      interval: 3s
      timeout: 3s
      retries: 10
    volumes:
      - ./services/synapse/synapse-adapters/adapter-postgres/db/init:/docker-entrypoint-initdb.d:ro
      - pgdata:/var/lib/postgresql/data

  # Single service using cargo-leptos to handle both frontend and backend
  synapse:
    depends_on:
      db:
        condition: service_healthy
    build:
      context: .
      dockerfile: services/synapse/Dockerfile
    working_dir: /workspace
    command: ["cargo", "leptos", "watch", "--project", "client-web"]
    volumes:
      - .:/workspace
      - synapse-data:/data
      - cargo-registry:/usr/local/cargo/registry
      - cargo-git:/usr/local/cargo/git
      - synapse-target:/workspace/target
    ports:
      - "3000:3000"
      - "4000:4000"
    environment:
      - RUST_LOG=debug
      - CONFIG_PATH=/data/synapse_config.json
      - PRIVATE_KEY_PATH=/data/key.path
      - AXUM_PORT=3000
      - LIBP2P_PORT=4000
      - ANNOUNCE=
      - BOOTSTRAP_LIST=
      - DATABASE_URL=postgres://postgres:example@db:5432/menexus_dev
      - LEPTOS_WASM_BINDGEN_VERSION=0.2.105
      - LEPTOS_TAILWIND_VERSION=v4.1.5

volumes:
  pgdata:
  cargo-registry:
  cargo-git:
  synapse-data:
  synapse-target:
