packages:
  - apps/*
  - services/*
  - packages/*

ignoredBuiltDependencies:
  - '@tailwindcss/oxide'
  - bcrypt
  - classic-level
  - esbuild

onlyBuiltDependencies:
  - '@ipshipyard/node-datachannel'
